// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gui.h"

void GUI::cb_CubeMap_i(Fl_Button*, void*) {
  DBG_cb();
}
void GUI::cb_CubeMap(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_CubeMap_i(o,v);
}

void GUI::cb_Reflections_i(Fl_Button*, void*) {
  NewButton_cb();
}
void GUI::cb_Reflections(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Reflections_i(o,v);
}

void GUI::cb_Left_i(Fl_Button*, void*) {
  Left_cb();
}
void GUI::cb_Left(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Left_i(o,v);
}

void GUI::cb_Right_i(Fl_Button*, void*) {
  Right_cb();
}
void GUI::cb_Right(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Right_i(o,v);
}

void GUI::cb_Roll_i(Fl_Button*, void*) {
  Up_cb();
}
void GUI::cb_Roll(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Roll_i(o,v);
}

void GUI::cb_Roll1_i(Fl_Button*, void*) {
  Down_cb();
}
void GUI::cb_Roll1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Roll1_i(o,v);
}

void GUI::cb_Tilt_i(Fl_Button*, void*) {
  TiltL_cb();
}
void GUI::cb_Tilt(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Tilt_i(o,v);
}

void GUI::cb_Tilt1_i(Fl_Button*, void*) {
  TiltR_cb();
}
void GUI::cb_Tilt1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Tilt1_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(120, 153, "GUI");
    uiw->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(120, 85, 70, 20, "CubeMap");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_CubeMap);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(120, 60, 70, 20, "Reflections");
      o->callback((Fl_Callback*)cb_Reflections);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(15, 15, 45, 40, "Left");
      o->callback((Fl_Callback*)cb_Left);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(65, 15, 45, 40, "Right");
      o->callback((Fl_Callback*)cb_Right);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(15, 60, 45, 40, "Roll Front");
      o->callback((Fl_Callback*)cb_Roll);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(65, 60, 45, 40, "Roll Back");
      o->callback((Fl_Callback*)cb_Roll1);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(15, 105, 45, 40, "Tilt Left");
      o->callback((Fl_Callback*)cb_Tilt);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(65, 105, 45, 40, "Tilt Right");
      o->callback((Fl_Callback*)cb_Tilt1);
      o->align(Fl_Align(FL_ALIGN_WRAP));
    } // Fl_Button* o
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();
}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::NewButton_cb() {
  scene->NewButton();
}

void GUI::Up_cb() {
  scene->Up();
}

void GUI::Down_cb() {
  scene->Down();
}

void GUI::Left_cb() {
  scene->Left();
}

void GUI::Right_cb() {
  scene->Right();
}

void GUI::TiltL_cb() {
  scene->Up1();
}

void GUI::TiltR_cb() {
  scene->Down1();
}
