// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  inline void cb_CubeMap_i(Fl_Button*, void*);
  static void cb_CubeMap(Fl_Button*, void*);
  inline void cb_Reflections_i(Fl_Button*, void*);
  static void cb_Reflections(Fl_Button*, void*);
  inline void cb_Left_i(Fl_Button*, void*);
  static void cb_Left(Fl_Button*, void*);
  inline void cb_Right_i(Fl_Button*, void*);
  static void cb_Right(Fl_Button*, void*);
  inline void cb_Roll_i(Fl_Button*, void*);
  static void cb_Roll(Fl_Button*, void*);
  inline void cb_Roll1_i(Fl_Button*, void*);
  static void cb_Roll1(Fl_Button*, void*);
  inline void cb_Tilt_i(Fl_Button*, void*);
  static void cb_Tilt(Fl_Button*, void*);
  inline void cb_Tilt1_i(Fl_Button*, void*);
  static void cb_Tilt1(Fl_Button*, void*);
public:
  void show();
  void DBG_cb();
  void NewButton_cb();
  void Up_cb();
  void Down_cb();
  void Left_cb();
  void Right_cb();
  void TiltL_cb();
  void TiltR_cb();
};
#endif
